"""Stage 14 — A2A transport TLS scaffold (KB_16 §"Transport security"). Honest: live ML-KEM TLS is Stage 18.

A2A traffic terminates at an OpenSSL-3.5 + oqs-provider sidecar (haproxy/stunnel) doing hybrid **ML-KEM-768+X25519**
key exchange + mTLS (both certs in an ML-DSA-65 trust chain). Per KB_13's algorithm matrix the **hybrid TLS itself is
Stage 18 (PQC Wave 2)** — this module emits the sidecar CONFIG + documents the deployment, but does NOT claim the
live PQC TLS is running (Rule 1a). The Python app stays on plain HTTP behind the sidecar (loopback).
"""
from __future__ import annotations

from typing import Any

# Hybrid groups + signature the oqs-provider sidecar negotiates (KB_13).
HYBRID_KEM_GROUPS = "X25519MLKEM768:X25519"
HYBRID_SIGNATURE = "mldsa65"


def haproxy_sidecar_config(*, frontend_port: int = 8443, backend_host: str = "backend",
                           backend_port: int = 8000) -> str:
    """Return a haproxy config for the oqs-provider hybrid-mTLS sidecar (Stage-18 deployment artefact)."""
    return f"""# Stage-18 oqs-provider hybrid mTLS sidecar (haproxy 2.9+ built against OpenSSL 3.5 + oqs-provider).
# Generated by backend/a2a/transport_tls.py — KB_16 trust boundary. NOT live until Stage 18 (KB_13 matrix).
global
    ssl-default-bind-curves {HYBRID_KEM_GROUPS}
defaults
    mode http
    timeout connect 5s
    timeout client 30s
    timeout server 30s
frontend a2a_tls
    bind :{frontend_port} ssl crt /etc/haproxy/certs/agent.pem ca-file /etc/haproxy/certs/a2a_roots.pem verify required
    # hybrid KEM groups: {HYBRID_KEM_GROUPS}; peer + server certs signed ML-DSA-65 ({HYBRID_SIGNATURE})
    default_backend app
backend app
    server app {backend_host}:{backend_port}   # plain HTTP on loopback; the sidecar enforces PQC TLS + mTLS
"""


def status() -> dict[str, Any]:
    """Honest status — the config is generated; the live PQC TLS is Stage 18."""
    return {"hybrid_kem_groups": HYBRID_KEM_GROUPS, "signature": HYBRID_SIGNATURE,
            "live_pqc_tls": False, "stage": "scaffold (Stage 14); live ML-KEM-768 mTLS = Stage 18 (KB_13)",
            "sidecar": "openssl 3.5 + oqs-provider via haproxy/stunnel (docker-compose.pqc.yml)"}


__all__ = ["haproxy_sidecar_config", "status", "HYBRID_KEM_GROUPS", "HYBRID_SIGNATURE"]
