#!/usr/bin/env bash
# Regenerate the VDA 5050 Pydantic models from the official upstream JSON schemas (schemas/*.json).
# Build-time (datamodel-code-generator, a dev dep). Emits a package (models/) because the schemas share definitions.
# NOTE: keep non-.json files (SCHEMAS_PROVENANCE.md) OUT of schemas/ — the generator parses every file in the dir.
#
# datamodel-code-generator emits an EMPTY models/__init__.py, which would clobber our root re-exports (and break
# `from integrations.vda5050.models import OrderMessage` in code + tests + CI). So this script RE-APPLIES the curated
# __init__ after codegen — keeping `compile_models.sh` the single source of truth for the generated package.
set -euo pipefail
cd "$(dirname "$0")/../.."   # backend/

python -m datamodel_code_generator \
  --input integrations/vda5050/schemas/ --input-file-type jsonschema \
  --output integrations/vda5050/models/ \
  --target-python-version 3.11 --formatters black isort

# Re-apply the curated __init__ (re-exports each topic's root model). Root class names are derived from the v2.1.0
# schema titles: order→OrderMessage, state→State, connection→Connection, instantActions→InstantActions,
# factsheet→AgvFactsheet (v3.0.0 would be MobileRobotFactsheet), visualization→Visualization.
cat > integrations/vda5050/models/__init__.py <<'PYEOF'
# generated by datamodel-codegen (per-topic modules); this __init__ is RESTORED by compile_models.sh after codegen
# (datamodel-code-generator emits an empty __init__ — compile_models.sh overwrites it with these re-exports).
"""VDA 5050 v2.1.0 Pydantic models — per-topic modules GENERATED from the official upstream JSON schemas.

The topic modules (`order.py`, `state.py`, …) are generated by `datamodel-code-generator` from
`integrations/vda5050/schemas/*.json` (real VDA5050 repo schemas @ tag **2.1.0**, MIT — see `../SCHEMAS_PROVENANCE.md`);
regenerate with `../compile_models.sh` (which re-applies these re-exports). This `__init__` re-exports each topic's
root message model for ergonomic imports.
"""
from .connection import Connection
from .factsheet import AgvFactsheet
from .instantActions import InstantActions
from .order import Edge, Node, OrderMessage
from .state import State
from .visualization import Visualization

__all__ = ["OrderMessage", "Node", "Edge", "State", "Connection", "InstantActions",
           "AgvFactsheet", "Visualization"]
PYEOF

echo "Generated integrations/vda5050/models/ from integrations/vda5050/schemas/*.json (+ restored curated __init__)"
